baseURL = '/'
languageCode = 'en-us'
title = 'Colonialbiker Blog Site'
theme = 'binario'
pagination.pagerSize = "6" # Number of elements per page in pagination
summaryLength = 50

[Params]
  description = "Colonialbiker BLog Website"
  dateFormat = "January 02, 2006"
  authorbox = true
  comments = true


[Params.Entry]
  meta = ["date", "categories", "tags"]
  toc = true
  tocOpen = true

[Params.Author]
  name = "Sumukh Kesarla"
  bio = "Sumukh's true identity is unknown. Maybe he is a successful blogger or writer :)"

[Params.Social]
  email = "colonialbiker123@gmail.com"
  linkedin = "sumukh-kesarla"

[Params.Share]
  linkedin = true
